prometheus-node-exporter:
    hostRootFsMount: false

kubeApiServer:
  enabled: true
  tlsConfig:
    serverName: kubernetes
    insecureSkipVerify: true

prometheus:
  prometheusSpec:
    podMetadata:
      annotations:
        "consul.hashicorp.com/connect-inject": 'true'
        "consul.hashicorp.com/connect-service": "prometheus-kube-prometheus-prometheus"

grafana:
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      searchNamespace: ALL
      enabled: true
      label: grafana_dashboard
      folder: /tmp/dashboards
      provider:
        foldersFromFilesStructure: true
      annotations:
        k8s-sidecar-target-directory: /tmp/dashboards/Infrastructure/Kubernetes
  plugins:
  - grafana-piechart-panel
  - digrich-bubblechart-panel
  - grafana-clock-panel
