prometheus-node-exporter:
    hostRootFsMount: false

kubeApiServer:
  enabled: true
  tlsConfig:
    serverName: kubernetes
    insecureSkipVerify: true

grafana:
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      searchNamespace: ALL
      enabled: true
      label: grafana_dashboard
      folder: /tmp/dashboards
      provider:
        foldersFromFilesStructure: true
      annotations:
        k8s-sidecar-target-directory: /tmp/dashboards/kubernetes
  plugins:
  - grafana-piechart-panel
  - digrich-bubblechart-panel
  - grafana-clock-panel