version: "3.8"

services:
  # Infrastructure services
  consul:
    image: consul:latest
    ports:
        - "8500:8500"
        - "8300:8300"
    networks:
      - webshop
    volumes:
    - ./deploy/compose/consul/config:/config
    - ./deploy/compose/consul/_data:/data
    command: 'agent -config-dir=/config -data-dir=/data -bind ''{{ GetPrivateInterfaces | attr "address" }}'' -client ''{{ GetPrivateInterfaces | attr "address" }}'' -bootstrap'
  # consul-agent:
  #   image: 'consul:latest'
  #   hostname: consul-agent
  #   container_name: consul-agent
  #   command: 'agent -join consul -config-dir=/config -bind ''{{ GetPrivateInterfaces | attr "address" }}'' -client ''{{ GetPrivateInterfaces | attr "address" }}'''
  #   volumes:
  #   - ./deploy/compose/consul-agent/config:/config
  #   - ./deploy/compose/consul-agent/_data/consul:/data
  #   networks:
  #     - webshop
  #   depends_on:
  #     - consul
  consul-backup:
    image: consul_backup:latest
    container_name: consul-backup
    build:
      context: ./src/consul_backup
      dockerfile: Dockerfile
    networks:
      webshop: null
    depends_on:
      - consul
    volumes:
      - './deploy/compose/_data/consul/backup:/backup/'
    command: consul-backup
  vault:
    image: 'vault:latest'
    networks:
      webshop: null
    depends_on:
      - consul
    ports:
      - '8200:8200'
    cap_add:
      - IPC_LOCK
    volumes:
      - './deploy/compose/vault/config/:/config'
    command: server -config=/config/vault.hcl
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - webshop
  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "Password_123"
      ACCEPT_EULA: "Y"
    container_name: "sqlserverdb"
    user: root # required when docker-host is on windows
    networks:
      - webshop
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data
    ports:
      - "1433:1433"

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - webshop
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  # dps:
  #   image: defreitas/dns-proxy-server
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - MG_LOG_LEVEL=ERROR
  #     - MG_REGISTER_CONTAINER_NAMES=1
  #   hostname: dns.microservices
  #   networks:
  #     webshop:
  #       ipv4_address: 10.1.0.10

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - "9091:9090"
  #   networks:
  #     - webshop
  #   # network_mode: host
  #   volumes:
  #     - prometheus:/prometheus
  #   #   - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml

  # Business services
  catalog:
    image: catalog:latest
    build:
      context: ./
      dockerfile: Catalog/Dockerfile
    deploy:
      replicas: 1
    environment:
      - CONSUL_HTTP_ADDR=webshop_consul_1:8500
      - ASPNETCORE_BASEPATH=/catalog
      - ConnectionStrings:CatalogDbContext=Server=sqlserverdb,1433;Database=Catalog;User Id=sa;Password=Password_123;MultipleActiveResultSets=true
      - ServiceDiscovery:Enabled=true
      - ServiceDiscovery:SelfRegistration=true
      - ServiceDiscovery:Datacenter=webshop-dc
      - ServiceDiscovery:ServiceName=Catalog
      - ServiceDiscovery:Port=80
      - ServiceDiscovery:Tags:0=CatalogService
      - ServiceDiscovery:Tags:1=urlprefix-/catalog/ strip=/catalog #fabio
      - ServiceDiscovery:WaitTime=30
      - DistributedTracing:UseExporter=jaeger
      - DistributedTracing:Jaeger:ServiceName=Catalog
      - DistributedTracing:Jaeger:Host=webshop_jaeger_1
      - DistributedTracing:Jaeger:Port=6831
      - Swagger:disableHttps=true
    ports:
      - 80
    networks:
      webshop: null
  # catalog-sidecar:
  #   image: 'nicholasjackson/consul-envoy:v1.8.3-v1.14.4'
  #   container_name: catalog-sidecar
  #   environment:
  #     CONSUL_HTTP_ADDR: 'consul:8500'
  #     CONSUL_GRPC_ADDR: 'consul:8502'
  #     SERVICE_CONFIG: /config/catalog.json
  #     CENTRAL_CONFIG: /central_config/catalog-defaults.hcl
  #   volumes:
  #     - './deploy/compose/service_config:/config'
  #     - './deploy/compose/central_config:/central_config'
  #   command:
  #     - consul
  #     - connect
  #     - envoy
  #     - '-sidecar-for'
  #     - catalog-v1
  #   depends_on:
  #     - consul
  #   network_mode: 'service:catalog'


networks:
  webshop:
    name: webshop
    driver: bridge

volumes:
  mssql-server-linux-data:
    driver: local
  rabbitmq:
    driver: local
  portainer:
    driver: local
  prometheus:
    driver: local
