site_name: Webshop
theme:
  name: material
nav:
    - Home: 'index.md'
    - Analysis:
         - 'Use cases': 'analysis/functional-usecases.md'
    #     - 'Tye': 'setup/tye.md'
    #     - 'Docker-Compose': 'setup/docker-compose.md'
    #     - 'Kubernetes': 'setup/kubernetes.md'
    - About:
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'
dev_addr: '0.0.0.0:8080'