apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: infrastructure
spec:
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
  ingress:
    enabled: false
  allInOne:
    options:
      query:
        base-path: /jaeger
