# Choose an optional name for the datacenter
global:
  datacenter: webshop
  acls:
    manageSytemACLs: true

# Enable the Consul Web UI via a NodePort
ui:
  enabled: true
  service:
    enabled: true
    type: 'NodePort'

# Enable Connect for secure communication between nodes
connectInject:
  enabled: true
# Enable CRD Controller
controller:
  enabled: true

ingressGateways:
  enabled: false
  # defaults:
  #   replicas: 1 #default = 2, but they cannot be on the same node. there is only one node on docker-desktop
  # gateways:
  #   - name: ingress-gateway
  #     service:
  #       type: LoadBalancer

client:
  enabled: true

# Use only one Consul server for local development
server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
  # extraConfig: |
  #   {
  #     "ui_config": {
  #       "content_path": "/consul"
  #     }
  #   }

syncCatalog:
  enabled: false
  k8sAllowNamespaces: ['webshop']
  k8sDenyNamespaces: ['kube-system', 'kube-public']