# Choose an optional name for the datacenter
global:
  datacenter: webshop

# Enable the Consul Web UI via a NodePort
ui:
  service:
    type: 'NodePort'

# Enable Connect for secure communication between nodes
connectInject:
  enabled: true
# Enable CRD Controller
controller:
  enabled: true

ingressGateways:
  enabled: true
  defaults:
    replicas: 1 #default = 2, but they cannot be on the same node. there is only one node on docker-desktop
  gateways:
    - name: ingress-gateway
      service:
        type: LoadBalancer

client:
  enabled: true

# Use only one Consul server for local development
server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0

syncCatalog:
  enabled: false
  k8sAllowNamespaces: ['webshop']
  k8sDenyNamespaces: ['kube-system', 'kube-public']