
global:
  enabled: true
ui:
  enabled: true
# dev:
#   enabled: true
injector:
  enabled: true
server:
  affinity: ""
  ha:
    enabled: true
    replicas: 1
    config: |
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "0.0.0.0:8200"
        cluster_address = "0.0.0.0:8201"
      }
      storage "consul" {
        path = "vault"
        address = "HOST_IP:8500"
        advertise_addr = "HOST_IP:8300"
        scheme = "http"
      }
