dashboard:
  enabled: true
  domain: traefik.localhost

additionalArguments:
  - "--metrics.prometheus=true"

kubernetes:
  namespaces:
    - default
    - kube-system

consul:
  enabled: true
  endpoint: "consul-consul-server:8500"
  datacenter: webshop
  watch: true
  exposedByDefault: true
  prefix: traefik