dashboard:
  enabled: true
  domain: traefik.localhost

additionalArguments:
  - "--metrics.prometheus=true"
  - "--tracing.jaeger=true"
  - "--tracing.jaeger.samplingServerURL=http://jaeger-agent.infrastructure.svc:5778/sampling"
  - "--tracing.jaeger.localAgentHostPort=jaeger-agent.infrastructure.svc:6831"

kubernetes:
  namespaces:
    - default
    - kube-system

consul:
  enabled: true
  endpoint: "consul-consul-server:8500"
  datacenter: webshop
  watch: true
  exposedByDefault: true
  prefix: traefik